sudo: required
services:
  - docker

before_install:
  - docker build -t lightningnemesis/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true lightningnemesis/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dokcer-react-new"
  env: "Dokcer-react-new-env"
  bucket_name: "elasticbeanstalk-ap-south-1-378657656846"
  bucket_path: "dokcer-react-new"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"